data sum;
set meg.test2 end=end nobs=nobs;
array orig(25) item1-item25;
array sums(25) sum1-sum25;
do i = 1 to 25;
 sums(i)+orig(i);
end;
if end then do;
 do j = 1 to 25;
  Item=vname(orig(j));
  ItemDifficultyIndex=sums(j)/nobs;
  sum=sums(j);
  output;
 end;
end;
drop i j sum1-sum25;
data sum;
set sum;

if ItemDifficultyIndex ge .70 then Level='+';
if ItemDifficultyIndex lt .30 then Level='-';

title "Item Difficulty (Easiness/Popularity/Prevalence) Indexes";
title3 "Analysis for All Items";
title5 "+ = Easy Item         - = Difficult Item";
proc print;
var Item ItemDifficultyIndex Level;
run;
title;
proc means Data=sum n mean std min max maxdec=2 fw=5;
title "Analysis for All Items";
var ItemDifficultyIndex;
run;
data sum;
set sum;
if Level =' ';
title "Item Difficulty (Easiness/Popularity/Prevalence) Indexes";
title3 "Analysis for Retained Items";
proc print;
var Item ItemDifficultyIndex;
run;
title;
proc means Data=sum n mean std min max maxdec=2 fw=5;
title3 "Analysis for Retained Items";
var ItemDifficultyIndex;
run;
title;
